### ISSUE TITLE
Consider using RFID NFC Stickers to eliminate the need for QR code scanning

### ISSUE THREAD

**Issue by ktogias** [komis1/cocotrace#1]
Great App and idea!

You could stick an RFID NFC sticker on each desk, so that students do not have to use their phone's camera and scan the QR code. Once they have downloaded the app and given it permission to use phone's NFC, they put their phone on the desk, or pass it near the tag, and their position is automatically recorded. 

The cost of RFID NFC Stickers is quite low. See for example the prices on e-bay: https://www.ebay.com/itm/184467852679

**Comment by komis1** [comment]
Thank you Kostas! Unfortunately, while NFC tags are super-cheap, not every mobile phone has NFC reading capabilities... we resorted to QR scanning since the camera is ubiquitously available. 
Also NFC reading means a native app - don't think it can be done with web technologies only. This was also a requirement due to the need to deploy quickly, rather than spend more time developing native apps.
Nevertheless, if we manage to find human resources to do it, then we definitely should. If you want to join the effort, it'd be great!
